name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.9, '3.10', '3.11', '3.12', '3.13', '3.14']
      fail-fast: false


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.X
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    # for py3.14 only (pillow)
    - name: Install JPEG libraries
      run: sudo apt-get update && sudo apt-get install -y libjpeg-dev

    - name: Install the package itself
      run: |
          pip install poetry
          poetry install --with dev

    - name: Test with pytest
      run: |
        poetry run pytest --cov-report term --cov=easydev

    - name: coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
